config/routes.rb
Kasira::Application.routes.draw do

  get "productos/autocomplete"
  get "productos/new_menu"
  get "productos/menu"
  get "productos/other"
  get "clientes/best_clients"
  get "clientes/autocomplete"
  
  resources :clientes
  resources :productos
  resources :facturas
  resources :pedidos, :only => [:show] do
    member do
      get "facturar"
      post "facturado"
    end
  end
  resources :mesas do
    resources :pedidos, :only => [:new, :create, :edit, :update, :show]
  end

  get "login"   => "user_sessions#new",        :as => "login"
  get "logout"  => "user_sessions#destroy",    :as => "logout"
  resources :user_sessions
  resources :users do
    member do
      post "suspender"
    end
  end
  
  root 'mesas#index'

end

app/models/cliente.rb
# == Schema Information
#
# Table name: clientes
#
#  id                       :integer          not null, primary key
#  nombre                   :string(255)
#  direccion                :string(255)
#  numero_de_identificacion :string(255)
#  telefono                 :string(255)
#  email                    :string(255)
#  created_at               :datetime
#  updated_at               :datetime
#

class Cliente < ActiveRecord::Base
  has_many :facturas
	validates :nombre, :numero_de_identificacion, :presence => true
  validates_id :numero_de_identificacion, :message => "Cédula incorrecta"
  
  sync :all
	def self.autocomplete(params)
		clientes = Cliente.where("numero_de_identificacion like ?", "%#{params}%")
    clientes = clientes.map do |cliente|
      {
        :id => cliente.id,
        :label => cliente.numero_de_identificacion + " / " + cliente.nombre,
        :value => cliente.numero_de_identificacion,
        :cedula => cliente.numero_de_identificacion,
        :nombre => cliente.nombre,
        :direccion => cliente.direccion,
        :telefono => cliente.telefono
      }
    end
    clientes 
	end
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_filter :require_login
  before_action :find_cliente, only: [:show, :edit, :update, :destroy]
	enable_sync
	def index
    # @clientes = Cliente.order("created_at").page(params[:page]).per_page(6)
    @clientes = Cliente.all
    respond_to do |format|
      format.html
      format.js { render json: @clientes }
    end
  end

  def autocomplete
    respond_to do |format|
      format.json { render :json => Cliente.autocomplete(params[:term]) }
    end
  end

	def new
		@cliente= Cliente.new
    respond_to do |format|
      format.html
      format.js { render json: @cliente }
    end
	end

	def create
    @cliente = Cliente.new(cliente_params)
    respond_to do |format|
      @cliente.save
      format.html { redirect_to clientes_path, :notice => "Almacendao" }
      format.js { render "success" }
    end
	end
  
  def show
    respond_to do |format|
      format.js{ render "show" }
    end
  end


  def edit
    respond_to do |format|
      format.js{ render "new_or_edit" }
    end
  end

  def update
    respond_to do |format|
      @cliente.update(cliente_params)
      format.js { render "success"}
      format.json { respond_with_bip(@cliente) }
    end
  end

  def best_clients
    @clientes = Cliente.all
    respond_to do |format|
      format.js
    end
  end

	private
	def find_cliente
		@cliente = Cliente.find(params[:id])
	end

	def cliente_params
		params.require(:cliente).permit(:nombre, :direccion, :numero_de_identificacion, :telefono, :email)
	end
end

app/views/clientes/_best_clients.html.erb
<legend>Tus Mejores Clientes</legend>
<div class="row">
	<!--Pattern HTML-->
	<div id="pattern" class="pattern">
		<ul class="list img-list">
			<% @clientes.each do |cliente| %>
			<li>
				<div class="li-img">
					<img  class="img-thumbnail" id="show_identicon" width = "50px" src="/images/identicon.png">
				</div>
				<div class="li-text">
					<h4 class="li-head"><%= cliente.nombre  %></h4>
					<p class="li-summary"><%= cliente.direccion  %></p>
					<p class="li-action"><%= cliente.numero_de_identificacion  %></p>
				</div>
				<div class="li-money">
					<span class="text-success">$223.23</span>
					<small class="text-muted">consumo</small>
				</div>
			</li>
			<% end %>
		</ul>
	</div>
	<!--End Pattern HTML-->
</div>

app/views/clientes/_clientes.html.erb
<div class="clients white-backg col-xs-12 col-md-4">
  <div class="col-md-4 col-xs-3">
    <img  class="img-thumbnail" id="show_identicon" width="80px" src="/images/identicon.png">
  </div>
  <div class="col-md-6 col-xs-7 text-left">
    <%= cliente.nombre %><br>
    <span class ="identificacion"><%= cliente.numero_de_identificacion %></span><br>
    <span class ="domicilio"><%= cliente.direccion %></span>
  </div>
  <div class="col-md-2 col-xs-2">
   <%=  link_to 'Editar', edit_cliente_path(cliente), :remote => true, :rel=> 'tooltip', :title=>'Mostrar','data-toggle' =>  "modal", 'data-target' => '#myModal', class: "btn btn-default btn-xs"%>
 </div>
</div>

app/views/clientes/_form.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
  <h3 class="modal-title" id="myModalLabel">Cliente</h3>
</div>
<%= form_for(@cliente, :remote => true) do |f| %>
<div class="modal-body">
  <div class="field">
    <div class="col-md-6">
      <div class="row text-center">
        <div class="col-lg-12">
          <p></p>
          <img  class="img-thumbnail" id="show_identicon" width="110px" src="/images/identicon.png">
          <p></p><p></p>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <%= f.label :nombre %>
      <%= f.text_field :nombre, required:true, class: "form-control"%>
      <%= f.label :numero_de_identificacion, "C.I O RUC" %>
      <%= f.text_field :numero_de_identificacion, required:true, class: "form-control", id: "identificacion"%>
    </div>
    <div class="rosw">
      <%= f.label :direccion %>
      <%= f.text_field :direccion, class: "form-control" %>
      <%= f.label :telefono %>
      <%= f.text_field :telefono, class: "form-control" %>
      <%= f.label :email %>
      <%= f.text_field :email, class: "form-control" %>
    </div>
  </div>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
  <%= f.submit 'Guardar', class: "btn btn-primary", :remote => true %>
</div>
<% end %>

app/views/clientes/_new.html.erb
<%= form_for(@cliente, :remote => true) do |f| %>
<div class="client row">
  <div class="col-md-2 text-center">
    <img  class="img-thumbnail client-identicon" id="show_identicon" width="110px" src="/images/identicon.png"><br>
    <small class="text-muted">Este es tu avatar</small>
  </div>
  <div class="col-md-4">
    <%= f.label :nombre %>
    <%= f.text_field :nombre, required:true, class: "form-control"%>
    <%= f.label :numero_de_identificacion, "C.I O RUC" %>
    <%= f.text_field :numero_de_identificacion, required:true, class: "form-control", id: "identificacion"%>
    <%= f.label :direccion %>
    <%= f.text_field :direccion, class: "form-control" %>
  </div>
  <div class="col-md-5">
    <%= f.label :telefono %>
    <%= f.text_field :telefono, class: "form-control" %>
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control" %><br>
    <%= f.submit 'Guardar', class: "btn btn-primary", :remote => true %>
  </div>
</div>
<% end %>

app/views/clientes/_show.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
  <h1 class="modal-title" id="myModalLabel">Información</h1>
</div>
<div class="modal-body">
  <div class="col-md-2 text-center">
    <img  class="img-thumbnail" id="show_identicon" width="100px" src="/images/identicon.png">
  </div>
  <div class="col-md-10">
    <p>
      <strong>Nombre:</strong>
      <%= @cliente.nombre %>
      <p>
        <strong>Número de identificación:</strong>
        <span class="identificacion"><%= @cliente.numero_de_identificacion %></span>
      </p>
      <p>
        <strong>Dirección:</strong>
        <%= @cliente.direccion %>
      </p>
    </p>
  </div>
  <div class="more-info">
    <p>
      <strong>Teléfono:</strong>
      <%= @cliente.telefono %>
    </p>
    <p>
      <strong>Email:</strong>
      <a href="mailto:"><%= @cliente.email%></a>
    </p>
  </div>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">Salir</button>
  <%= link_to 'Editar', edit_cliente_path(cliente), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#myModal', class: "editar_edit"}%>
</div>

app/views/clientes/best_clients.js.erb
$(".tab-content").html("<%= j render('clientes/best_clients') %>");
window.Helpers.GetIdenticon.identicon_clients();

app/views/clientes/index.html.erb
<legend>Clientes</legend>
<%= link_to "Nuevo", new_cliente_path%>
<div id="list-clients">
	<%= sync partial: 'list_clientes', collection: @clientes, as: :cliente %>
    <%= sync_new partial: 'list_clientes', resource: Cliente.new %>
</div>

app/views/clientes/index.js.erb
$('#list-clients').html("<%= j render('clientes/clientes', clientes: @clientes) %>");
$.setAjaxPagination();
window.Helpers.GetIdenticon.list_clients();

app/views/clientes/new.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
  <h1 class="modal-title" id="myModalLabel">Nuevo cliente</h1>
</div>
<%= form_for @cliente do |f| %>
<div class="modal-body">
  <div class="field">
    <%= f.label :nombre %>
    <%= f.text_field :nombre, required:true %>
    <%= f.label :numero_de_identificacion, "C.I O RUC" %>
    <%= f.text_field :numero_de_identificacion, required:true%>
    <%= f.label :direccion %>
    <%= f.text_field :direccion %>
    <%= f.label :telefono %>
    <%= f.text_field :telefono %>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
  <%= f.submit 'Guardar', class: "btn btn-primary" %>
</div>
<% end %>

app/views/clientes/new.js.erb
$(".tab-content").html("<%= j render('clientes/new') %>");
window.Helpers.GetIdenticon.generate();

app/views/clientes/new_or_edit.js.erb
m = $('#content_modal');
m.html('<%= j(render partial: 'form', locals: {cliente: @cliente}) %>');
window.Helpers.FormsHelper.init();

app/views/clientes/show.js.erb
m = $('#content_modal');
m.html('<%= j(render partial: 'show', locals: {cliente: @cliente}) %>');
window.Helpers.FormsHelper.init();
window.Helpers.GetIdenticon.show();

app/views/clientes/success.js.erb
<%- if @cliente.errors.any? %>
  $('#content_modal').html('<%= escape_javascript(render('form')) %>');
  <%- @cliente.errors.full_messages.each do |msg|%>
    alertify.error("<%=j msg %>");
  <%- end %>
<%- else %>
  $("#myModal").modal("hide");
  $('body').removeClass('modal-open');
  $('.modal-backdrop').remove();
  window.Helpers.init_datatables();
  alertify.success("Cliente guardado");
<%- end %>