config/routes.rb
Kasira::Application.routes.draw do

  get "productos/autocomplete"
  get "productos/new_menu"
  get "productos/menu"
  get "productos/other"
  get "clientes/best_clients"
  get "clientes/autocomplete"
  
  resources :clientes
  resources :productos
  resources :facturas
  resources :pedidos, :only => [:show] do
    member do
      get "facturar"
      post "facturado"
    end
  end
  resources :mesas do
    resources :pedidos, :only => [:new, :create, :edit, :update, :show]
  end

  get "login"   => "user_sessions#new",        :as => "login"
  get "logout"  => "user_sessions#destroy",    :as => "logout"
  resources :user_sessions
  resources :users do
    member do
      post "suspender"
    end
  end
  
  root 'mesas#index'

end

app/models/pedido.rb
# == Schema Information
#
# Table name: pedidos
#
#  id         :integer          not null, primary key
#  mesa_id    :integer
#  total      :float
#  facturado  :boolean          default(FALSE)
#  created_at :datetime
#  updated_at :datetime
#

class Pedido < ActiveRecord::Base
	belongs_to :mesa
	belongs_to :user
	has_many :item_pedidos, dependent: :destroy
	has_many :productos, :through => :item_pedidos
	
	#nested
	accepts_nested_attributes_for :item_pedidos
	accepts_nested_attributes_for :item_pedidos, :allow_destroy => true

	before_validation :set_values;
	# after_update :set_items

	#real-time
  sync :all
	sync_touch :mesa
	
	def facturar(cliente)
		factura  = Factura.new(:tipo => "mesa", :subtotal_0 => self.subtotal_0, :subtotal_12 => self.subtotal_12, :descuento => self.descuento, :iva => self.iva, :total => self.total)
		if cliente[:cliente_id].empty?
			cliente = Cliente.new(:nombre => cliente[:nombre], :numero_de_identificacion => cliente[:numero_de_identificacion], :direccion => cliente[:direccion], :telefono => cliente[:telefono])
			cliente.save
			factura.cliente_id = cliente.id
		else
			factura.cliente_id = cliente[:cliente_id]
		end
		factura.numero = Factura.last ? Factura.last.numero + 1 : 1
		factura.fecha_de_emision = Time.now
		factura.fecha_de_caducidad = Time.now + 30.days
		factura.item_facturas = Factura.create_items_facturas(self.item_pedidos)
		factura
	end

	def update_mesa_from_factura
		self.update(:facturado =>  true)
		self.mesa.update(:ocupada => false)
	end

	def set_values
		self.numero = Pedido.last ? Pedido.last.numero + 1 : 1
		subtotal_0 = 0
		subtotal_12 = 0
		iva = 0
		self.item_pedidos.each do |item|
			unless item.producto_id.nil?
				producto = Producto.find item.producto_id
				cantidad = item.cantidad
				# item.tipo = "menu"
				iva_producto = (producto.precio_venta * 0.12).round(2)
				item.total = (producto.precio_venta * cantidad) #asigna valor total del item
				if producto.hasiva == true
					item.valor_unitario = (producto.precio_venta - iva_producto).round(2) #valor venta menos el iva 12
					item.iva = (iva_producto * cantidad)
					subtotal_12 = subtotal_12 + (item.valor_unitario * cantidad)
				else
					item.valor_unitario = producto.precio_venta
					subtotal_0 = subtotal_0 + (item.valor_unitario * cantidad)
					item.iva = 0
				end
				iva = iva + item.iva #suma iva de los productos
			end
		end
		self.iva = iva.round(2)
		self.subtotal_0 = subtotal_0
		self.subtotal_12 = subtotal_12
		self.total = subtotal_0 + subtotal_12 + self.iva
		self.total = self.total.round(2)
		self.descuento = 0
		self.mesa.update(:ocupada => true)
	end
end

app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
	before_filter :require_login
	before_action :find_mesa, only: [:new, :create, :edit, :update]
	before_action :set_pedido, only: [:edit, :update, :facturar]
  
  enable_sync

	def new
		@pedido = Pedido.new
		@pedido.item_pedidos.build
		respond_to do |format|
			format.html
			format.js{ render json: @pedido }
		end	
	end

	def show
		respond_to do |format|
			format.html
			format.js
		end
	end

	def create
		@pedido = Pedido.new(pedido_params.merge(user_id: current_user.id))
		@pedido.mesa = @mesa
		@pedido.save
		respond_to do |format|
			format.html {redirect_to root_path, :notice => "almacenado"}
			format.js{ render json: @pedido }
		end
	end

	def edit
    respond_to do |format|
			format.html
			format.js{ render json: @pedido }
    end
  end
  
  def update
    respond_to do |format|
      @pedido.update(pedido_params)
			format.html {redirect_to root_path, :notice => "Almacenado"}
			format.js{ render json: @pedido }
    end
  end
	
	def facturar
	  respond_to do |format|
			format.html
      format.js
    end
	end

	def facturado
		@pedido = Pedido.find(params[:id])
		@factura = @pedido.facturar(@_params)
		@factura.user = current_user
		if @factura.save
			@pedido.update(:facturado =>  true)
			@pedido.mesa.update(:ocupada => false)
			redirect_to facturas_path, :notice => "Factura Creada"
		else
			redirect_to facturas_path
			flash[:error] = 'Error al crear la factura'
		end
	end

	private

	def pedido_params
		params.require(:pedido).permit :mesa_id,
		:item_pedidos_attributes => [
			:descripcion,
			:precio_venta,
			:cantidad,
			:valor_unitario,
			:iva,
			:total,
			:producto_id,
			:id,
			:pedido_id,
			:_destroy
		]
	end
	
	def find_mesa
		# @mesa = Mesa.find_by_numero(params[:numero])
		@mesa = Mesa.find(params[:mesa_id])
	end

	def set_pedido
		# @pedido = Pedido.find_by_numero(params[:id])
		@pedido = Pedido.find(params[:id])
	end
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/views/pedidos/_cliente.html.erb
<div class="factura-mesa">
	<%= form_tag facturado_pedido_path do %>
	<div class="row-fix-div">
		<div class="col-md-3 col-xs-4 text-center">
			<img class="img-thumbnail" id="show_identicon" width="110px" src="/images/identicon.png">
		</div>
		<div class="col-md-8 col-xs-8">
			<input id="factura_tipo" name="factura[tipo]" type="hidden" value="normal">
			<div class="fields">
				<%= hidden_field_tag :cliente_id, params[:cliente_id], class: "cliente_id" %>
				<%= text_field_tag :numero_de_identificacion, params[:numero_de_identificacion], :required => true, class: "form-control-border numero_de_identificacion", :placeholder => "Cedula o R.U.C", id: "identificacion" %>
				<%= text_field_tag :nombre, params[:nombre], :required => true, class: "form-control-border nombre", :placeholder => "Nombre" %>
				<%= text_field_tag :direccion, params[:direccion], :required => true, class: "form-control-border direccion", :placeholder => "Direccion Domicilio" %>
				<%= text_field_tag :telefono, params[:telefono], :required => true, class: "form-control-border telefono", :placeholder => "Telefono" %>
			</div>
		</div>
	</div>
	<div class="valores col-md-12">
		<table class="table table-hover">
			<thead>
				<tr>
					<th>Producto</th>
					<th>Cantidad</th>
					<th>Precio</th>
					<th>Iva</th>
					<th>Total</th>
				</tr>
			</thead>
			<tbody>
				<% @pedido.item_pedidos.each do |item| %>
				<tr>
					<td><%= item.producto.nombre%></td>
					<td><%= item.cantidad %></td>
					<td>$ <%= item.valor_unitario %></td>
					<td>$ <%= item.iva %></td>
					<td>$ <%= item.total %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<div class="row">
			<div class="col-xs-4 col-xs-offset-6 text-right">
				<p>
					<strong>
						Subtotal 12%: <br>
						Subtotal 0%: <br>
						IVA: <br>
						Total: <br>
					</strong>
				</p>
			</div>
			<div class="col-xs-2">
				<strong>
					$ <%= @pedido.subtotal_12 %><br>
					$ <%= @pedido.subtotal_0 %><br>
					$ <%= @pedido.iva %><br>
					$ <%= @pedido.total %><br>
				</strong>
			</div>
		</div>
	</div>
	<div class="text-right col-md-12">
		<span class="btn btn-default volver-pedido">Volver</span>
		<%= submit_tag "Guardar", data: {disable_with: "Facturando..."}, class: "btn btn-success save-factura" %>
	</div>
	<% end %>
</div>				

app/views/pedidos/_form.html.erb
<h4>Mesa #<%=@mesa.numero%> </h4>
<div class="col-md-8 white-backg col-md-offset-2 pedido-camarero">
	<div class="pedido-form">
		<%= nested_form_for [@mesa, @pedido] do |f| %>
		<%= form_errors_for @pedido %>
		<div class="title-pedido">
			<h3 class="text-center title-pedido"><i class="flaticon-waiter"></i> Que desea Ordenar?</h3>
		</div>
		<div class="table-pedido">
			<table class="table" id="factura">
				<thead>
					<tr>
						<th>Producto</th>
						<th>Cantidad</th>
						<th>Precio</th>
						<th>Total</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<%= f.fields_for :item_pedidos, :wrapper => false do |item| %>
					<tr class="fields">
						<%= render 'items/pedidos', item:item %>
					</tr>
					<% end %>
					<tr>
						<td><%= f.link_to_add "", :item_pedidos, :class => "fa fa-plus text-info"%>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
		<div class="row-fix-div products-info col-md-12">
			<div class="col-md-4 col-xs-2">
				<span class="total_factura">
					<% if @pedido.total %>
					$<%= @pedido.total %>
					<% else %>
					$0.0
					<% end %>
				</span>
			</div>
			<div class="col-md-8 col-xs-10 text-right opcions">
				<% unless @pedido.mesa.nil? %>
				<%= link_to "Facturar", facturar_pedido_path(@pedido),remote: true, class: "ttip btn btn-default" %>
				<% end %>
				<%= f.submit :Guardar, class: "btn btn-info", data: {disable_with: "Almacenando"}%>
			</div>
		</div>
		<% end %>
	</div>
</div>

app/views/pedidos/edit.html.erb
<%= render 'form'  %>

app/views/pedidos/facturar.js.erb
$(".pedido-camarero").prepend('<%= j(render partial: 'pedidos/cliente', locals: {pedido: @pedido}) %>');
$(".factura-mesa").hide();
$(".factura-mesa").slideDown(500);
$(".pedido-form").slideUp();
window.Helpers.AutocompleteHelper.init_autocomplete();
window.Helpers.ShowFacturaMesa.show();
window.Helpers.GetIdenticon.generate();

app/views/pedidos/new.html.erb
<%= render 'form'  %>