config/routes.rb
Kasira::Application.routes.draw do

  get "productos/autocomplete"
  get "productos/new_menu"
  get "productos/menu"
  get "productos/other"
  get "clientes/best_clients"
  get "clientes/autocomplete"
  
  resources :clientes
  resources :productos
  resources :facturas
  resources :pedidos, :only => [:show] do
    member do
      get "facturar"
      post "facturado"
    end
  end
  resources :mesas do
    resources :pedidos, :only => [:new, :create, :edit, :update, :show]
  end

  get "login"   => "user_sessions#new",        :as => "login"
  get "logout"  => "user_sessions#destroy",    :as => "logout"
  resources :user_sessions
  resources :users do
    member do
      post "suspender"
    end
  end
  
  root 'mesas#index'

end

app/models/mesa.rb
# == Schema Information
#
# Table name: mesas
#
#  id         :integer          not null, primary key
#  numero     :integer          not null
#  ocupada    :boolean          default(FALSE)
#  created_at :datetime
#  updated_at :datetime
#

class Mesa < ActiveRecord::Base
	has_many :pedidos
	validates :numero, :numericality => { :greater_than_or_equal_to => 0, :less_than_or_equal_to => 99, :message => "Rango maximo de 0-99" }
	validates :numero, :uniqueness => :true
	sync :all
end

app/controllers/mesas_controller.rb
class MesasController < ApplicationController
  before_filter :require_login
  enable_sync

	def index
		@mesa= Mesa.new
		@mesas = Mesa.all
		respond_to do |format|
      format.html
      format.js { render json: @mesas }
    end
	end

	def new
		@mesa= Mesa.new
		respond_to do |format|
      format.html
      format.js
    end
	end

	def create
		@mesa = Mesa.new(mesa_params)
		@mesa.save
		respond_to do |format|
			format.html
			format.js
		end
	end
	
  def edit
    @mesa = Mesa.find(params[:id])
    fresh_when @mesa
  end

  def update
    @mesa = Mesa.find(params[:id])
    respond_to do |format|
      if @mesa.update_attributes(mesa_params)
        format.html { redirect_to @mesa, notice: 'mesa was successfully updated.' }
        format.js { redirect_via_turbolinks_to @mesa, notice: 'Mesa was successfully updated.' }
      else
        format.html { render action: "edit" }
        format.js { render action: "edit" }
      end
    end
	end

	private
	def set_mesa
		@mesa = Mesa.find(params[:id])
	end

	def mesa_params
		params.require(:mesa).permit(:numero)
	end
end

app/helpers/mesas_helper.rb
module MesasHelper
end

app/views/sync/mesas/_list_mesas.html.erb
<li>
	<div class="content">
		<% unless mesa.ocupada?%>
		<div class="info-mesa">
			<span class="numero">Mesa <%= mesa.numero%></span>
			<span class="consumo pull-rigth">$ 0.00</span>
			<div class="icon"><span class="flaticon-cutlery6"></span></div>
			<div class="opcions-mesa"><%= link_to "Pedido", new_mesa_pedido_path(mesa), class: "label label-success"%></div>
		</div>
		<% else %>
		<div class="info-mesa">
			<span class="numero">Mesa <%= mesa.numero%></span>
			<span class="consumo pull-rigth">$ <%= mesa.pedidos.last.total %></span>
			<div class="icon"><span class="flaticon-man288"></span></div>
			<div class="opcions-mesa"><%= link_to "Pedido", edit_mesa_pedido_path(mesa, mesa.pedidos.last), class: "label label-success"%></div>
		</div>
		<% end %>
	</div>
</li>