config/routes.rb
Kasira::Application.routes.draw do

  get "productos/autocomplete"
  get "productos/new_menu"
  get "productos/menu"
  get "productos/other"
  get "clientes/best_clients"
  get "clientes/autocomplete"
  
  resources :clientes
  resources :productos
  resources :facturas
  resources :pedidos, :only => [:show] do
    member do
      get "facturar"
      post "facturado"
    end
  end
  resources :mesas do
    resources :pedidos, :only => [:new, :create, :edit, :update, :show]
  end

  get "login"   => "user_sessions#new",        :as => "login"
  get "logout"  => "user_sessions#destroy",    :as => "logout"
  resources :user_sessions
  resources :users do
    member do
      post "suspender"
    end
  end
  
  root 'mesas#index'

end

app/models/producto.rb
# == Schema Information
#
# Table name: productos
#
#  id            :integer          not null, primary key
#  nombre        :string(255)      not null
#  codigo        :string(255)
#  categoria     :string(255)
#  precio_compra :float
#  precio_venta  :float
#  hasiva        :boolean
#  stock         :integer
#  tipo          :string(255)
#  created_at    :datetime
#  updated_at    :datetime
#

class Producto < ActiveRecord::Base
	#relations
  has_many :ingreso_productos
  has_many :item_facturas
  has_many :item_pedidos
  # belongs_to :item_factura
  # has_one :kardex
  # has_many :factura_compras_productos
  # has_many :factura_compras, :through => :factura_compras_productos
  # has_many :canjes
  accepts_nested_attributes_for :ingreso_productos, :allow_destroy => true, reject_if: :all_blank
	validates :nombre, :precio_compra, :precio_venta, :presence => true
  
  def self.autocomplete(params)
    productos = Producto.where("nombre like ?", "%#{params}%")
    productos = productos.map do |producto|
    {
      :id => producto.id,
      # :label => ingreso.producto.nombre + "/" + "Lote:" + ingreso.lote ,
      :label => producto.nombre,
      :value => producto.nombre,
      :precio_venta => producto.precio_venta,
      :id_ingreso => producto.id,
      :iva => producto.hasiva
    }
    end
    productos
  end

end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_filter :require_login
  before_action :set_producto, only: [:show, :edit, :update]
  before_action :find_caducados, only: [:caducado, :alerta]
  
  def index
    # ['Plato Fuerte','Ceviche','Sopa','Bebida','Postre','De la casa', 'Desayuno','Almuerzo', 'Otros']
    @menu = Producto.where(:tipo => "menu")
    @plato_fuertes , @ceviches, @sopas, @bebidas, @postres, @casa = [], [], [], [], [], []
    @menu.each do |item|
      @plato_fuertes << item if item.categoria == 'Plato Fuerte'
      @ceviches << item if item.categoria == 'Ceviche'
      @sopas << item if item.categoria == 'Sopa'
      @bebidas << item if item.categoria == 'Bebida'
      @postres << item if item.categoria == 'Postre'
      @casa << item if item.categoria == 'De la casa'
    end
    respond_to do |format|
      format.html
      # format.json { render json: ProductosDatatable.new(view_context) }
    end
  end

  def menu
    @menu = Producto.where(:tipo => "menu")
  end

  def other
    @producto = Producto.where(:tipo => "producto")
  end

  def autocomplete
    respond_to do |format|
      format.json { render :json => Producto.autocomplete(params[:term]) }
    end    
  end

  def new
    @producto=  Producto.new
    @producto.tipo = "producto"
    @producto.ingreso_productos.build
    respond_to do |format|
      format.js{ render "new_or_edit" }
    end
  end

  def new_menu
    @producto=  Producto.new
    @producto.tipo = "menu"
    @producto.ingreso_productos.build
    respond_to do |format|
      format.js{ render "new_or_edit" }
    end
  end

  def show
    respond_to do |format|
      format.js
    end
  end
  
  def edit
    respond_to do |format|
      format.js{ render "new_or_edit" }
    end
  end

  def create
    @producto = Producto.new(producto_params)
    respond_to do |format|
      @producto.save
      format.js{ render "success" }
    end
  end

  def update
    respond_to do |format|
      @producto.update(producto_params)
        format.js{ render "success" }
    end
  end

  # def caducado
  # end

  # def alerta
  #   if @caducados.empty? == true
  #     redirect_to root_path
  #   end    
  # end

  private 
  
  def producto_params
    params.require(:producto).permit :nombre,
    :codigo,
    :categoria,
    :precio_venta,
    :precio_compra,
    :hasiva,
    :tipo,
    :ingreso_productos_attributes => [
      :lote,
      :cantidad,
      :fecha_caducidad,
      :producto_id,
      :_destroy,
      :id,
    ]                                    
  end  
  
  def set_producto
      @producto = Producto.find(params[:id])
  end

  def find_caducados
    @caducados = IngresoProducto.where(:fecha_caducidad =>Time.now.end_of_day..Time.now.months_since(4)).where("cantidad != '0'")
    @hoy = Date.today    
  end
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/productos/_form.html.erb
<%= nested_form_for @producto, :remote => true do |f| %>
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
  <% if @producto.tipo == "menu" %>
  <h3 class="modal-title fa fa-cutlery" id="myModalLabel"> Nuevo Plato</h3>
  <% else %>    
  <h3 class="modal-title" id="myModalLabel">Nuevo Producto</h3>
  <% end %>
</div>
<div class="modal-body field">
  <ul class="list-inline row">
    <li class="col-md-4">
      <%= f.hidden_field :id %>
      <%= f.hidden_field :tipo %>
      <%= f.label :nombre %>
      <%= f.text_field :nombre, :class => "nombre_producto"%>
    </li>
    <li class="col-md-4">
      <%= f.label :codigo, "Código" %>
      <%= f.text_field :codigo %>
    </li>
  <% if @producto.tipo == "menu" %>
    <li class="col-md-4">
      <%= f.label :categoria,"Categoría" %>
      <%= f.select(:categoria, ['Plato Fuerte','Ceviche','Sopa','Bebida','Postre','De la casa', 'Desayuno','Almuerzo', 'Otros'], {}, { :class => 'form-control' }) %>
    </li>
  <% end %>
    <li class="col-md-4">
      <%= f.label :precio_compra, "Precio de compra" %>
      <%= f.number_field :precio_compra,:class => "precio_compra", :placeholder => "0.00", min: "0", step: "any"%>
    </li>
    <li class="col-md-4">
      <%= f.label :precio_venta %>
      <%= f.number_field :precio_venta, :placeholder => "0.00", min: "0", :step => "any" %>
    </li>
    <li class="col-md-4">
      <%= f.label :hasiva, "Tiene IVA?" %>
      <%= f.check_box :hasiva %>
    </li>
  </ul>
  <% unless @producto.tipo == "menu" %>
  <table class="table">
    <thead>
      <tr>
        <th>Fecha Caducidad</th>
        <th>Cantidad</th>
        <th>Lote</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
     <%= f.fields_for :ingreso_productos, :wrapper => false do |p| %>
     <tr class="fields">
       <%= render "productos/ingresos", p: p %>
     </tr>
     <% end %>
     <tr><td><%= f.link_to_add "", :ingreso_productos, :class => "fa fa-plus"%></td>
     </tr>
   </tbody>
 </table>
 <% end %>
</div>
<div class="modal-footer">
	<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
	<%= f.submit 'Guardar', class: "btn btn-primary"%>
</div>
<% end %>

app/views/productos/_ingresos.html.erb
<td><%= p.text_field :fecha_caducidad, :class => "datepicker" %></td>
<td><%= p.number_field :cantidad,:class => "cantidad_producto",:placeholder => "0", min: "0"%></td>
<td><%= p.text_field :lote %></td>
<td><%= p.link_to_remove '', :class => "delete_destroy fa fa-times text-danger" %></td>

app/views/productos/_productos.html.erb
<table class="data-table table-bordered" data-source="<%= productos_url(format: "json") %>">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Código</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>

app/views/productos/_show.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
  <h2 class="modal-title" id="myModalLabel"><%= @producto.nombre %></h2>
</div>
<div class="modal-body">
  <div class="row">
    <div class="col-md-6">
      <strong>Categoría:</strong>
      <%= @producto.categoria %><br>
      <strong>Código:</strong>
      <%= @producto.codigo %>
    </div>
    <div class="col-md-6">
      <strong>Precio de compra:</strong>
      <%= @producto.precio_compra %><br>
      <strong>Precio de venta:</strong>
      <%= @producto.precio_venta %><br>
      <strong>Incluye iva:</strong>
      <%= @producto.hasiva%>
      <!-- <strong>Stock:</strong>
      <%= @producto.stock%> -->
    </div>
  </div>
  <% unless @producto.ingreso_productos.empty? %>
  <legend>Detalles del producto:</legend>
  <table class="table table-hover">
    <thead class= "well">
      <tr>
        <th>Lote</th>
        <th>Cantidad</th>
        <th>Fecha de caducidad</th>
      </tr>
    </thead>
    <tbody>
      <% @producto.ingreso_productos.each do |detalle| %>
      <% unless detalle.cantidad == 0 %>
      <tr>
        <td><%= detalle.lote %></td>
        <td><%= detalle.cantidad %></td>
        <td><%= detalle.fecha_caducidad %></td>
      </tr>
      <% end %>
      <% end %>
    </tbody>
  </table>
  <% end %>  
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">Salir</button>
</div>

app/views/productos/index.html.erb
<div class="row white-backg">
	<legend>Productos</legend>
	<div class="white-backg">
		<%= link_to ' Nuevo Producto', new_producto_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#myModal',title: "Nuevo", class: "btn btn-info fa fa-plus btn-xs"}  %>
		<%= link_to ' Agregar Menu', productos_new_menu_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#myModal',title: "Nuevo", class: "btn btn-info fa fa-cutlery btn-xs"}  %>
	</div>
	<div class="all-products">
		<% @casa.each do |c| %>
		<div class="col-xs-12 col-md-4" style = "margin-bottom: 10px;">
			<div class="col-md-3 col-xs-3 category">
				<span class="flaticon-waiter menu-casa"></span>
			</div>
			<div class="col-md-6 col-xs-7 text-left">
				<%= c.nombre  %><br>
				Precio Venta: $<%= c.precio_venta  %>
				Precio Compra: $<%= c.precio_compra  %>
			</div>
			<div class="col-md-2 col-xs-2">
				<%= link_to "editar", edit_producto_path(c.id), class: "btn btn-xs btn-default",:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#myModal' %>
			</div>
		</div>
		<% end %>
		<% @plato_fuertes.each do |c| %>
		<div class="col-xs-12 col-md-4" style = "margin-bottom: 10px;">
			<div class="col-md-3 col-xs-3 category">
				<span class="flaticon-food14 circle-red"></span>
			</div>
			<div class="col-md-6 col-xs-7 text-left">
				<%= c.nombre  %><br>
				Precio Venta: $<%= c.precio_venta  %>
				Precio Compra: $<%= c.precio_compra  %>
			</div>
			<div class="col-md-2 col-xs-2">
				<%= link_to "editar", edit_producto_path(c.id), class: "btn btn-xs btn-default",:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#myModal' %>
			</div>
		</div>
		<% end %>
		<% @ceviches.each do |c| %>
		<div class="col-xs-12 col-md-4" style = "margin-bottom: 10px;">
			<div class="col-md-3 col-xs-3 category">
				<span class="flaticon-salty circle-green"></span>
			</div>
			<div class="col-md-6 col-xs-7 text-left">
				<%= c.nombre  %><br>
				Precio Venta: $<%= c.precio_venta  %>
				Precio Compra: $<%= c.precio_compra  %>
			</div>
			<div class="col-md-2 col-xs-2">
				<%= link_to "editar", edit_producto_path(c.id), class: "btn btn-xs btn-default",:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#myModal' %>
			</div>
		</div>
		<% end %>
		<% @sopas.each do |c| %>
		<div class="col-xs-12 col-md-4" style = "margin-bottom: 10px;">
			<div class="col-md-3 col-xs-3 category">
				<span class="flaticon-soup circle-green"></span>
			</div>
			<div class="col-md-6 col-xs-7 text-left">
				<%= c.nombre  %><br>
				Precio Venta: $<%= c.precio_venta  %>
				Precio Compra: $<%= c.precio_compra  %>
			</div>
			<div class="col-md-2 col-xs-2">
				<%= link_to "editar", edit_producto_path(c.id), class: "btn btn-xs btn-default",:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#myModal' %>
			</div>
		</div>
		<% end %>
		<% @bebidas.each do |c| %>
		<div class="col-xs-12 col-md-4" style = "margin-bottom: 10px;">
			<div class="col-md-3 col-xs-3 category">
				<span class="flaticon-root circle-blue"></span>
			</div>
			<div class="col-md-6 col-xs-7 text-left">
				<%= c.nombre  %><br>
				Precio Venta: $<%= c.precio_venta  %>
				Precio Compra: $<%= c.precio_compra  %>
			</div>
			<div class="col-md-2 col-xs-2">
				<%= link_to "editar", edit_producto_path(c.id), class: "btn btn-xs btn-default",:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#myModal' %>
			</div>
		</div>
		<% end %>
		<% @postres.each do |c| %>
		<div class="col-xs-12 col-md-4" style = "margin-bottom: 10px;">
			<div class="col-md-3 col-xs-3 category">
				<span class="flaticon-sweet9 postre"></span>
			</div>
			<div class="col-md-6 col-xs-7 text-left">
				<%= c.nombre  %><br>
				Precio Venta: $<%= c.precio_venta  %>
				Precio Compra: $<%= c.precio_compra  %>
			</div>
			<div class="col-md-2 col-xs-2">
				<span class="btn btn-xs btn-default">editar</span>
			</div>
		</div>
		<% end %>
	</div>
</div>
<!-- flaticon-glass35 -->

app/views/productos/new_or_edit.js.erb
m = $('#content_modal');
m.html('<%= j(render partial: 'form', locals: {producto: @producto}) %>');
// window.Helpers.ButtonsHelper.init();
window.Helpers.FormsHelper.init()
// window.Helpers.Datepicker.init_datepicker();

app/views/productos/show.js.erb
m = $('#content_modal');
m.html('<%= j(render partial: 'show', locals: {producto: @producto}) %>');

app/views/productos/success.js.erb
<%- if @producto.errors.any? %>
$('#content_modal').html('<%= escape_javascript(render('form')) %>');
window.Helpers.FormsHelper.init()
<%- @producto.errors.full_messages.each do |msg|%>
alertify.error("<%=j msg %>");
<%- end %>
<%- else %>
m = $('#content_modal');
// content = $("<div class='text-center text-white'><i class=' fa fa-check-circle fa-5x text-center'></i><h5>Almacendo</h5></div>")
m.toggleClass("hovered");
m.html('<%= j(render partial: 'shared/animation') %>');
// $('.spinner').html(content).fadeOut(1000).fadeIn(3000);

var hide_modal = function() {
  $("#myModal").modal("hide");
  $('body').removeClass('modal-open');
  $('.modal-backdrop').remove();
  $(".table-productos").html('<%= j render 'productos', productos: @productos %>');
  m.toggleClass("hovered");
  window.Helpers.init_datatables();
}
setTimeout(hide_modal, 1500);
<%- end %>